ls:
  packages/components/**/{src}:
    .dir: kebab-case
    .vue: kebab-case
    .ts: kebab-case
  site/docs/**:
    .dir: kebab-case
    .vue: kebab-case
    .ts: kebab-case
  packages/theme-chalk/src/**:
    .dir: kebab-case
    .less: kebab-case
  packages/hooks/**:
    .dir: kebab-case
    .ts: kebab-case
  packages/directives/**:
    .dir: kebab-case
    .ts: kebab-case

ignore:
  - .git
  - .vscode
  - .lintstagedrc.js
  - node_modules
  - packages/components/node_modules
  - packages/components/hview-ui
  - site/docs/.vitepress
  - site/docs/en-US
  - site/docs/vite.config.ts
