<template>
  <h-space>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
    <h-button>按钮</h-button>
  </h-space>
</template>
